### PR TITLE
Test lammps

### PR DESCRIPTION
**Pull request by PabloPiaggi**
Hi @GiovanniBussi , I added the example to test lammps in the folder ```test-lammps``` and I modified the file ```.github/workflows/ci.yml```.

### CODE REVIEW

**Comment by PabloPiaggi** [comment]
Hi @GiovanniBussi , I am writing to remind you that this PR is pending your review. Is this not passing the tests because of the changes I made? Let me know if changes are needed.

**Comment by GiovanniBussi** [comment]
Hi @PabloPiaggi I merged it now (in masterclass-2022).

I think the workflow fails since it needs to upload the packages and the required token is not available in pull requests. I will check if now that it is merged it works as expected. Thanks!

**Comment by GiovanniBussi** [comment]
Hi @PabloPiaggi it seems everything is working now, I am closing this (I already merged your suggestion). Thanks again! Giovanni

**Comment by PabloPiaggi** [comment]
Perfect! Thanks.

**Pull request closed without merging**
